name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - use: actions/setup-node@v1
      - run: npm install
      - run: npm prettier
